import { everythingai, praivatesearch, whatagityear, qdurllm, pokemonbot, sentrev, proteinviz, proteinesm, greenfitai, biomedpapers, amplipiper, booksmixer, supaseqs, word2html, tinysd, pitchgen } from "./index";
export const projectArray = [
    {
        name: "everything-ai",
        description: "Your fully proficient, AI-powered and local chatbot assistant🤖",
        image: everythingai,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://www.github.com/AstraBert/everything-ai",
    },
    {
        name: "PrAIvateSearch",
        description: "Own your AI, search the web with it🌐😎",
        image: praivatesearch,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://www.github.com/AstraBert/PrAIvateSearch",
    },
    {
        name: "qdurllm",
        description: "Search your favorite websites and chat with them, on your desktop🌐",
        image: qdurllm,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://www.github.com/AstraBert/qdurllm",
    },
    {
        name: "SenTrEv",
        description: "Simple customizable evaluation for text retrieval performance of Sentence Transformers embedders on PDFs",
        image: sentrev,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://www.github.com/AstraBert/SenTrEv",
    },
    {
        name: "Pokemon-Bot",
        description: "Discord bot that knows a lot about Pokemons :)",
        image: pokemonbot,
        type: "Open Source",
        hostedLink: "https://huggingface.co/spaces/as-cle-bert/pokemon-bot",
        githubLink: "https://www.github.com/AstraBert/Pokemon-Bot",
    },
    {
        name: "ProteinViz",
        description: "Your open-source alternative to AlphaFold3🚀",
        image: proteinviz,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://www.github.com/AstraBert/proteinviz",
    },
    {
        name: "GreenFit AI",
        description: "Find out about sustainability in your favorite sport clothing brands, in just one click!",
        image: greenfitai,
        type: "Open Source",
        hostedLink: "https://huggingface.co/spaces/greenfit-ai/greenfit-ai",
        githubLink: "https://www.github.com/greenfit-ai/greenfit-ai",
    },
    {
        name: "What a Git Year!",
        description: "Simple Gradio app to showcase your GitHub achievements in the past year",
        image: whatagityear,
        type: "open source",
        hostedLink: "https://huggingface.co/spaces/as-cle-bert/what-a-git-year",
        githubLink: "https://www.github.com/AstraBert/what-a-git-year",
    },
    {
        name: "BiomedicalPapersBot",
        description: "A Gradio bot to retrieve PubMed papers' title, doi, authors and publication date based on general search terms or on specific publication names",
        image: biomedpapers,
        type: "Open Source",
        hostedLink: "https://huggingface.co/spaces/as-cle-bert/BioMedicalPapersBot",
        githubLink: "https://www.github.com/AstraBert/BioMedicalPapersBot",
    },
    {
        name: "AmpliPiper",
        description: "AmpliPiper is a comprehensive workflow based on BASH scripting, Python and R for analyzing high-throughput amplicon sequencing data for multiple samples and loci. The pipeline performs various tasks, including raw read demultiplexing, filtering, consensus sequence reconstruction, species identification and phylogenetic analysis.",
        image: amplipiper,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://github.com/nhmvienna/AmpliPiper",
    },
    {
        name: "books-mixer-ai",
        description: "Mix and twist your favorite books with the power of AI!📖.",
        image: booksmixer,
        type: "Open Source",
        hostedLink: "https://www.booksmixerai.xyz/",
        githubLink: "https://github.com/AstraBert/books-mixer-ai",
    },
    {
        name: "pitchgen-bot",
        description: "Great pitches for great ideas: make it easy with AI!🗣️",
        image: pitchgen,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://github.com/AstraBert/pitchgen-bot",
    },
    {
        name: "SupaSeqs",
        description: "Basically BLAST, but written in PostgreSQL😉",
        image: supaseqs,
        type: "Open Source",
        hostedLink: "",
        githubLink: "https://github.com/AstraBert/SupaSeqs",
    },
    {
        name: "Proteins-With-ESM",
        description: "Predict the whole sequence and 3D structure of masked protein sequences with ESM by @evolutionaryscale",
        image: proteinesm,
        type: "Open Source",
        hostedLink: "https://huggingface.co/spaces/as-cle-bert/proteins-with-esm",
        githubLink: "https://www.github.com/shivabhattacharjee/muxik-backend",
    },
    {
        name: "Word-Doc-2-HTML",
        description: "Python Desktop application to convert Word Documents to HTML - based on mammoth-python",
        image: word2html,
        type: "Open Source",
        hostedLink: "https://raw.githubusercontent.com/AstraBert/Word-Doc-2-HTML/main/application/Word-Doc-2-HTML.0.0.0.exe",
        githubLink: "https://github.com/AstraBert/Word-Doc-2-HTML",
    },
    {
        name: "awesome-tiny-sd",
        description: "Tiny stable diffusion chatbot based on segmind/small-sd to generate images upon text prompts.",
        image: tinysd,
        type: "Open Source",
        hostedLink: "https://huggingface.co/spaces/as-cle-bert/awesome-tiny-sd",
        githubLink: "https://github.com/AstraBert/awesome-tiny-sd",
    },
];
